### ISSUE TITLE
Know any algorithm in Java?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/java#4]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Java](https://github.com/AllAlgorithms/java) this case

**Comment by Muskan-goyal6** [comment]
I would like to do this

**Comment by Sanghamitra1234** [comment]
> Added isogram problem in hashing #50
